# Generated by Django 5.0.6 on 2024-06-05 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_country_popular_cities_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='monthly_weather_avg',
        ),
    ]
