# Generated by Django 5.0.6 on 2024-06-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_country_monthly_weather_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='monthly_weather_avg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
