# Generated by Django 5.0.6 on 2024-06-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_city_name_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name_type',
            field=models.CharField(choices=[('City', 'City'), ('Village', 'Village'), ('Island', 'Island'), ('Town', 'Town')], default='City', max_length=10),
        ),
    ]
